cabal-version: 3.0
name:          blockchainlang
version:       0.1.0.0

library
    exposed-modules: AST, Parser
    hs-source-dirs:  src
    default-language: GHC2021
    build-depends:
        base   ^>= 4.18
      , parsec

test-suite tests
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Tests.hs
    default-language: GHC2021
    build-depends:
        base             ^>= 4.18
      , blockchainlang
